#!/usr/bin/env bash

FILENAME=$@

if [ -f $FILENAME ]; then
    exit
fi

cat << EOF >> $FILENAME
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <cmath>
#include <queue>
#include <stack>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>

using namespace std;

#define endl '\n'


int main() {
    ios::sync_with_stdio(false);
    cout.precision(10);

    return 0;
}
EOF

vim $FILENAME
